### ISSUE TITLE
Debian 9: missing libnagios-plugin-perl package

### ISSUE THREAD

**Issue by vvidic** [perfsonar/nagios#10]
Need to include it in minor-packages for perfsonar-centralmanagement install to work.

**Comment by vvidic** [comment]
Upstream dead for this package, replaced by libmornitoring-plugin-perl in jessie.

**Comment by laeti-tia** [comment]
@vvidic so no additional package needed to backport?  Does this new libmonitoring-plugin-perl dependency works for both Jessie, Stretch and Xenial?

**Comment by vvidic** [comment]
On Mon, Jun 05, 2017 at 05:28:30AM -0700, Antoine Delvaux wrote:
> @vvidic so no additional package needed to backport?  Does this new
> libmonitoring-plugin-perl dependency works for both Jessie, Stretch
> and Xenial?

I backported libmonitoring-plugin-perl from stretch to jessie
and updated the checks to use Monitoring::Plugin instead of
Nagios::Plugin.

Package tests are green now for Jessie+Xenial+Stretch.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
