### ISSUE TITLE
http and dns nagios check

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/nagios#16]
We have 2 new pscheduler tests: pscheduler-test-http and pscheduler-test-dns.  If we want to be able to run those test as part of a MaDDash mesh, we would need to have corresponding nagios plugins.

**Comment by arlake228** [comment]
I can probably also come up with a more generic check that allows you to grab arbitrary fields out of esmond and compare to thresholds so we don't have to do this every time and adding new checks is more of a convenience than a necessity.
