### ISSUE TITLE
traceroute_check number of paths is Avg

### ISSUE THREAD

**Issue by igarny** [perfsonar/nagios#18]
Hello Andy,

It would be nice to have the traceroute nagios check evaluation not based on the **Average**, but on the **Max** value.
Here is an example of the output:
```
PS_CHECK_TRACEROUTE OK - Average number of paths is 1.000 | Count=2;; Min=1;; Max=1;; Average=1;; Standard_Deviation=0;;
```

**Comment by arlake228** [comment]
This is probably worth looking at for a future release. I don't know how much thought went into the current behavior.

**Comment by igarny** [comment]
As discussed: In practice there is no issue around the calculation of the number of the paths.
The implementation does account for the number of various paths discovered during the specified / assessed period with collected measurements. There is only one value provided, which essentially means AVG = MIN = MAX.
