### ISSUE TITLE
perfSONAR Nagios installation

### ISSUE THREAD

**Issue by igarny** [perfsonar/nagios#6]
Hi guys,

I am looking at the perfSONAR Nagios GitHub submodule and I am trying to deploy it on a testing instance. My assumption was that it should be somewhat straightforward and self- adjusting, but I do not find it like that. 
I have installed perl-perfSONAR_PS-Nagios.noarch.

I see there are a lot of symlinks in the lib subfolder that need adjustment. I also notice that these almost match the folder structure in the toolkit deployment, BUT there are several similar structures.
For instance:
/opt/perfsonar_ps/toolkit/lib/perfSONAR_PS/Utils/DNS.pm
/opt/perfsonar_ps/ls_registration_daemon/lib/perfSONAR_PS/Utils/DNS.pm
/opt/perfsonar_ps/mesh_config/lib/perfSONAR_PS/Utils/DNS.pm
/opt/perfsonar_ps/regular_testing/lib/perfSONAR_PS/Utils/DNS.pm
/opt/perfsonar_ps/serviceTest/lib/perfSONAR_PS/Utils/DNS.pm

Is there a more appropriate structure that the others?

I am also missing something called QueryObjectFactory.pm

Best regards,
Ivan

**Comment by arlake228** [comment]
See the README file. Change to the directory where you checked out git and run the following:
git submodule init
git submodule update

Alternatively you could have used the --recursive option with you initial "git clone" command. This is all in the README. For future reference, you will need to do the same for any of the perl components.
