### ISSUE TITLE
Nagios throughput check alarming levels usability

### ISSUE THREAD

**Issue by igarny** [perfsonar/nagios#7]
Hi guys,

I am looking at the Nagios tests...
I see nagios/bin/check_throughput_owdelay.pl and /nagios/bin/check_throughput.pl kind of sharing same purpose....anyway I could not find proper parameters for the first one, but the latter one worked...kind of.
The problem with the working one is the evaluation. How exactly do you use it like this?

nagios/bin/check_throughput.pl -u http://geant.net/esmond/perfsonar/archive -d 62.40.106.147 -s 62.40.106.131 -r 9000 -w 1 -c 2
PS_CHECK_THROUGHPUT OK - Average throughput is 0.993Gbps | Count=2;; Min=0.992365;; Max=0.993754;; Average=0.9930595;; Standard_Deviation=0.000982171319068115;;

This one demonstrates that Throughput is OK only if the Warning and Critical values are above the measured throughput.
To me this makes no sense, but I know you are doing proper evaluation, so I am not sure if I am on the right script or you are putting a different meaning behind the critical and warning values.

Best regards,
Ivan

**Comment by arlake228** [comment]
The checks assume a basic familiarity with standard nagios checks and practices. See https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

What you want is "-w 2:" and "-c 1:". See the link above for what that means. 

If you'd like to create an issue about better documentation go ahead,but the thresholds follow standard nagios practice and will not change.

check_throughput_owdelay.pl provides a richer set of thresholds based on the latency of the path. There is a help screen, if you can't figure it out from that then a) you probably don't need to be using it or b) can wait for better documentation.

**Comment by igarny** [comment]
Hi Andy,

I have been programming Nagios tests since 2011 and I bet you have not even checked anything about the issue. I believe your assumptions here are wrong.

**Comment by igarny** [comment]
If you could please comment on this:

nagios/bin/check_throughput.pl -u http://geant.org/esmond/perfsonar/archive -d 62.40.106.147 -s 62.40.106.131 -r 9000 -w 1 -c 2
PS_CHECK_THROUGHPUT OK - Average throughput is 0.993Gbps | Count=2;; Min=0.991869;; Max=0.993809;; Average=0.992839;; Standard_Deviation=0.0013717871555019;;

nagios/bin/check_throughput.pl -u http://geant.org/esmond/perfsonar/archive -d 62.40.106.147 -s 62.40.106.131 -r 9000 -w 0.8 -c 1
PS_CHECK_THROUGHPUT WARNING - Average throughput is 0.993Gbps | Count=2;; Min=0.991869;; Max=0.993809;; Average=0.992839;; Standard_Deviation=0.0013717871555019;;

nagios/bin/check_throughput.pl -u http://geant.org/esmond/perfsonar/archive -d 62.40.106.147 -s 62.40.106.131 -r 9000 -w 0.8 -c 0.9
PS_CHECK_THROUGHPUT CRITICAL - Average throughput is 0.993Gbps | Count=2;; Min=0.991869;; Max=0.993809;; Average=0.992839;; Standard_Deviation=0.0013717871555019;;

**Comment by arlake228** [comment]
Why don't you and I have a zoom chat so we can address your concerns as opposed to going back and forth in an issue. Let me know in slack when you're available.

**Comment by igarny** [comment]
Many apologies here. Obviously I have been blind and omitting the syntax.
Many thanks for the special attention
